version: "3.5"

services:
  app-assay:
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: app-assay
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8083:8083"
    volumes:
      - "./configs/config.yml:/configs/config.yml"
    depends_on:
      - mariadb 
      - redis 
      - mqtt 
      - minio 
    networks:
      - app-net 

  mariadb:
    image: mariadb:11.5.2
    container_name: "mariadb"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "./data/mysql:/var/lib/mysql"
      - "./log/mysql:/var/log/mysql"
      - "./conf/mysql:/etc/mysql"
    networks:
      - app-net 

  redis:
    image: redis:7.4.1
    container_name: redis 
    ports:
      - "6379:6379"
    networks:
      - app-net 
  
  mqtt: 
    image: ncarlier/mqtt:latest
    container_name: "mqtt"
    ports:
      - "1883:1883"
    networks:
      - app-net

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z.fips
    container_name: minio 
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server --console-address ":9001" http://minio/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "./data/minio/data1:/data1"
      - "./data/minio/data2:/data2"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
