version: "3.5"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
      - "1935:1935"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./dist:/usr/share/nginx/html"
      - "/var/log/nginx:/var/log/nginx"
      # 推流文件夹
      - "/var/share/nginx/html/hls:/var/share/nginx/html/hls"
    networks:
      - app-net 

  app-assay:
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: app-assay
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8083:8083"
    volumes:
      - "./configs/config.yml:/configs/config.yml"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - mysql
      - redis 
      - mqtt 
      - minio 
    networks:
      - app-net 

  app-hik:
    build:
      context: . 
      dockerfile: Dockerfile-hik
    container_name: app-hik
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      LD_LIBRARY_PATH: "/app/libs/lib"
    ports:
      - "8082:8082"
    volumes:
      - "./hik/configs/config.yml:/app/configs/config.yml"
      - "/tmp:/tmp"
    depends_on:
      - app-assay
    networks:
      - app-net

  mysql:
    image: mysql:9.1.0
    container_name: web-server-mysql
    environment:
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "./sql:/docker-entrypoint-initdb.d"
      - "/etc/mysql/conf.d:/etc/mysql/conf.d"
      - "/var/lib/mysql:/var/lib/mysql"
      - "/var/log/mysql:/var/log/mysql"
    networks:
      - app-net

  redis:
    image: redis:7.4.1
    container_name: redis 
    ports:
      - "6379:6379"
    networks:
      - app-net 
  
  mqtt: 
    image: emqx:5.8.2
    container_name: web-server-mqtt
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - "/etc/openvas:/etc/openvas"
      - "/etc/gvm:/etc/gvm"
      - "/var/log/gvm:/var/log/gvm"
    networks:
      - app-net

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z-cpuv1
    container_name: minio 
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server --console-address ":9001" http://minio/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "/var/lib/minio/data1:/data1"
      - "/var/lib/minio/data2:/data2"
    networks:
      - app-net
  
  webrtc-streamer:
    image: mpromonet/webrtc-streamer
    container_name: webrtc-streamer
    ports:
      - "8000:8000"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
