version: "3.5"

services:
  nginx:
    image: nginx 
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./dist:/usr/share/nginx/html"
      - "/var/log/nginx:/var/log/nginx"
    networks:
      - app-net 
  app-assay:
    build: 
      context: . 
      dockerfile: Dockerfile 
    container_name: app-assay
    restart: always
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8083:8083"
    volumes:
      - "./configs/config.yml:/configs/config.yml"
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    depends_on:
      - mariadb 
      - redis 
      - mqtt 
      - minio 
    networks:
      - app-net 

  app-hik:
    build:
      context: . 
      dockerfile: Dockerfile-hik
    container_name: app-hik
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      LD_LIBRARY_PATH: "/app/libs/lib"
    ports:
      - "8082:8082"
    volumes:
      - "./hik/configs/config.yml:/app/configs/config.yml"
      - "/tmp:/tmp"
    depends_on:
      - app-assay
    networks:
      - app-net

  mariadb:
    image: mariadb:11.5.2
    container_name: "mariadb"
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "123"
      TZ: "Asia/Shanghai"
    ports:
      - "3306:3306"
    volumes:
      - "./sql:/docker-entrypoint-initdb.d"
      - "/var/lib/mysql:/var/lib/mysql"
      - "/var/log/mysql:/var/log"
      - "/etc/mysql:/etc/mysql"
    networks:
      - app-net 

  redis:
    image: redis:7.4.1
    container_name: redis 
    ports:
      - "6379:6379"
    networks:
      - app-net 
  
  mqtt: 
    image: greenbone/mqtt-broker:latest
    container_name: "mqtt"
    ports:
      - "1883:1883"
    networks:
      - app-net

  minio:
    image: minio/minio:RELEASE.2024-10-13T13-34-11Z-cpuv1
    container_name: minio 
    environment:
      MINIO_ROOT_USER: "minioadmin"
      MINIO_ROOT_PASSWORD: "minioadmin"
    command: server --console-address ":9001" http://minio/data{1...2}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "/var/lib/minio/data1:/data1"
      - "/var/lib/minio/data2:/data2"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
