name: "assay"
version: "0.0.1"
mode: "debug"
port: 8083
time_location: "Asia/Shanghai"

mysql:
  dsn: "root:123@tcp(mysql:3306)/assay?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai"
  max_open_conn: 20
  max_idle_conn: 10
  max_conn_life_time: 100
  
redis:
  addr: "redis:6379"
  password: ""
  
jwt:
  key: "D#IPy!JRyyG4@WcrTOpgcNw8x6VF@R"
  salt: "!dRtGP-zwwU98dh)%+vyN3~yyZm=96"
  duration: 2678400

Cat:
  name: "/dev/ttyUSB0"
  baud: 115200
  read_timeout: 500 # ms
  size: 8
  stop_bits: 1
  parity: 78 # 'N' 

mqtt:
  addr: "mqtt:1883"
  quiesce: 250 # ms
  username: ""
  password: ""

minio:
  end_point: "minio:9000"
  access_key_id: "minioadmin"
  secret_access_key: "minioadmin"
  user_ssl: false

static_oss:
  domain: "http://localhost:9000"
  bucket: "assay.static"

dynamic_oss:
  domain: "http://localhost:9000"
  bucket: "assay"

text:
  width: 64
  height: 16
  url: "http://192.168.1.240:8084/command/y5c-524-01004"
  
